HoneyShop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('shop/', include('shop.urls')),
    path('blog/', include('blog.urls')),
    path('checkout/', include('checkout.urls')),
    path('order/', include('order.urls')),
    path('external_api_services/', include('external_api_services.urls')),

]

if settings.DEBUG:
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.PostList.as_view(), name='blog'),
    path('category/<str:slug>', views.PostsByCategory.as_view(), name='category'),
    path('post/<str:slug>', views.SinglePost.as_view(), name='post'),
    path('search/', views.Search.as_view(), name='search'),
    path('like-comment/', views.like_comment, name='like_comment'),
]

shop/urls.py
from django.urls import path, include

from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.Shop.as_view(), name='shop'),
    path('category/<str:slug>', views.ProductsByCategory.as_view(), name='category'),
    path('product/<str:slug>', views.DetailProduct.as_view(), name='product'),
    path('search/', views.Search.as_view(), name='search'),
    path('wishlist/', views.WishListView.as_view(), name='wishlist'),
    path('to-wishlist/', views.wishlist_button_action, name='add_or_remove_to_wishlist'),
    path('wishlist/clear/', views.clear_wishlist, name='clear_wishlist'),
    path('cart/', include('cart.urls'))
]

order/models.py
from django.conf import settings
from django.db import models

from phonenumber_field import modelfields

from checkout.models import DeliveryOptions, PaymentOptions
from shop.models import Product


class Order(models.Model):
    """Model to represent an order of user."""

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Користувач')
    recipient_first_name = models.CharField(verbose_name="Ім'я отримувача", max_length=100)
    recipient_last_name = models.CharField(verbose_name="Прізвище отримувача", max_length=100)
    recipient_patronymic = models.CharField(verbose_name="По-батькові отримувача", max_length=100)
    recipient_phone_number = modelfields.PhoneNumberField(verbose_name='Номер телефону отримувача')
    delivery_option = models.ForeignKey(DeliveryOptions, on_delete=models.CASCADE, verbose_name="Спосіб доставки")
    city = models.CharField(verbose_name='Місто', max_length=50, blank=True, null=True)
    street = models.CharField(verbose_name='Вулиця', max_length=50, blank=True, null=True)
    house = models.CharField(verbose_name='Будинок', max_length=6, blank=True, null=True)
    flat = models.CharField(verbose_name='Квартира', max_length=5, blank=True, null=True)
    delivery_service_department = models.CharField(verbose_name='Відділення служби доставки', max_length=256, blank=True,
                                                   null=True)
    payment_option = models.ForeignKey(PaymentOptions, verbose_name='Спосіб оплати', on_delete=models.CASCADE)
    billing_status = models.BooleanField(verbose_name='Здійснено оплату', default=False)
    total_price = models.DecimalField(verbose_name='Загальна сума оплати', max_digits=7, decimal_places=0)
    created_at = models.DateTimeField(verbose_name='Дата додавання', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='Дата оновлення', auto_now=True)

    class Meta:
        ordering = ('-created_at',)
        verbose_name = 'Замовлення'
        verbose_name_plural = 'Замовлення'

    def __str__(self):
        return f'Замовлення №{str(self.pk)}'

    def get_recipient(self):
        """Get the full name of the recipient."""
        return f'{self.recipient_last_name} {self.recipient_first_name} {self.recipient_patronymic}'


class OrderItem(models.Model):
    """Model to represent an item in an order."""

    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name='Замовлення')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар')
    price = models.DecimalField(max_digits=7, decimal_places=0, verbose_name='Вартість')
    quantity = models.PositiveIntegerField(default=1, verbose_name='Кількість')

    class Meta:
        verbose_name = 'Позиція замовлення'
        verbose_name_plural = 'Позиції замовлення'

    def __str__(self):
        return f'№{str(self.pk)} (замовлення №{str(self.order.pk)})'

    def total_price(self):
        """Calculate the total price for the order item."""
        return self.quantity * self.price

templates/inc/_alert.html
<div class="max-w-1000">
    {% for message in messages %}
        <div id="liveAlertPlaceholder">
        {% if message.tags == 'error' %}
            <div class="alert alert-danger alert-dismissible" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert"
                        aria-label="Close"></button>
            </div>
        {% else %}
            <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert"
                        aria-label="Close"></button>
            </div>
        {% endif %}
    {% endfor %}
    </div>
</div>

templates/inc/_base_single_comment.html
{% load static %}

<img class="user-photo comment-author-photo" alt="" src="{% if comment.user.photo %}{{ comment.user.photo.url }}
                                                  {% else %}{% static 'img/default_avatar.jpg' %}{% endif %}">
<div class="comment-details">
    <h5 class="comment-author mb-1">{{ comment.get_user }}</h5>
    <p class="comment-date mb-0"><i class="fa fa-calendar-alt me-2"></i>{{ comment.created_at }}</p>
    <p class="comment-body text-background my-2">{{ comment.body }}</p>
    <div class="comment-tools">
        {% block comment_tools %}{% endblock %}
        {% if comment.children %}
            <div class="reply-list-collapse-button tool-item me-0">
                <button class="btn btn-link-mod" type="button" data-bs-toggle="collapse"
                        data-bs-target="#reply-list-{{ comment.id }}" aria-expanded="false"
                        aria-controls="reply-list-{{ comment.id }}">
                            <span class="collapsed">
                                <i class="fa-solid fa-chevron-down fa-sm"></i>
                                Показати всі відповіді ({{ comment.children.count }})
                            </span>
                    <span class="expanded">
                                <i class="fa-solid fa-chevron-up fa-xs"></i>Згорнути всі відповіді ({{ comment.children.count }})
                            </span>
                </button>
            </div>
        {% endif %}
    </div>
</div>

templates/inc/_carousel.html
{% load static %}

<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="{% static 'img/slide/slider-01.jpg' %}" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="{% static 'img/slide/slider-02.jpg' %}" class="d-block w-100" alt="...">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls"
            data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls"
            data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

templates/inc/_footer.html
<footer class="mt-auto">
    <div class="container">
        <div class="footer-main row text-center">
            <div class="footer-about col-md pt-3">
                <div class="footer-logo brand">
                    <a href="{% url 'home' %}">MedOK</a>
                </div>
                <div class="footer-description">
                    <span>Інтернет-магазин справжнього меду</span>
                </div>
                <div class="footer-social d-flex align-items-center justify-content-center py-3">
                    <a href="https://www.facebook.com/yurii.onyshchuk96/" target="_blank">
                        <i class="fa fa-facebook" aria-hidden="true"></i>
                    </a>
                    <a href="https://twitter.com/yurii_onyshchuk/" target="_blank">
                        <i class="fa fa-twitter" aria-hidden="true"></i>
                    </a>
                    <a href="https://www.linkedin.com/in/yurii-onyshchuk/" target="_blank">
                        <i class="fa fa-linkedin" aria-hidden="true"></i>
                    </a>
                    <a href="https://www.instagram.com/yura.onyshchuk/" target="_blank">
                        <i class="fa fa-instagram" aria-hidden="true"></i>
                    </a>
                </div>
            </div>
            <div class="footer-menu col-md-3 order-2 order-md-1 pt-3">
                <ul class="footer-menu-box ps-0 mb-0">
                    <li class="list-group-item"><a href="{% url 'home' %}">Головна</a></li>
                    <li class="list-group-item"><a href="{% url 'shop:shop' %}">Магазин</a></li>
                    <li class="list-group-item"><a href="{% url 'blog:blog' %}">Блог</a></li>
                    <li class="list-group-item"><a href="{% url 'about' %}">Про&nbsp;нас</a></li>
                    <li class="list-group-item"><a href="{% url 'contacts' %}">Контакти</a></li>
                </ul>
            </div>
            <div class="footer-contact col-md order-1 order-md-2 pt-3">
                <h5>Зв'яжіться з нами:</h5>
                <ul class="footer-contact-box ps-0 mb-0">
                    <li class="list-group-item">
                        <a href="tel:+380976011377">
                            <i class="fa fa-phone pe-1" aria-hidden="true"></i>
                            <span>+38 097 601 13 77</span></a>
                    </li>
                    <li class="list-group-item">
                        <a href="mailto:yura.onyshchuk@gmail.com">
                            <i class="fa fa-envelope pe-1" aria-hidden="true"></i>
                            <span>yura.onyshchuk@gmail.com</span></a>
                    </li>
                    <li class="list-group-item">
                        <a href="https://www.google.com/maps/place/50%C2%B009'08.3%22N+26%C2%B049'30.2%22E/@50.1350663,26.8039408,13.5z/data=!4m5!3m4!1s0x0:0x565865a7af96e204!8m2!3d50.1522906!4d26.8250575"
                           target="_blank">
                            <i class="fa fa-map-marker pe-1" aria-hidden="true"></i>
                            <span>Хмельницька&nbsp;обл., Шепетівський&nbsp;р&#8209;н.,<br>с.&nbsp;Путринці, пров.&nbsp;Шкільний,&nbsp;13</span></a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="footer-info row">
            <div class="info-box col text-center py-2">
                <span>Всі права захищені<br>© Інтернет-магазин MedOK 2022</span>
            </div>
        </div>
    </div>
</footer>

templates/inc/_header.html
{% load static %}
<header>
    <div id="topbar" class="topbar d-flex align-items-center fixed-top">
        <div class="container-lg topbar-info d-flex align-items-center justify-content-center justify-content-md-end">
            <i class="bi bi-phone d-flex align-items-center me-4"><a href="tel:+380976011377">+38 097 601 13 77</a></i>
            <i class="bi bi-clock d-flex align-items-center"><span>Пон - Пт: 09:00 - 18:00</span></i>
        </div>
    </div>
    <nav id="navbar" class="navbar navbar-expand-md navbar-transparent fixed-top">
        <div class="container-lg">
            <a class="navbar-brand brand me-0" href="{% url 'home' %}">MedOK</a>
            <div class="navbar-toolbar d-flex order-md-2">
                <ul class="toolbar-list list-unstyled d-flex align-items-center mb-0">
                    <li class="nav-item cart me-3 me-sm-4 me-md-3">
                        <a class="tool-link cart-link" href="{% url 'shop:cart:cart_detail' %}">
                            <i class="fa-solid fa-basket-shopping"></i>
                            {% with cart|length as amount %}
                                <span style="display: {% if amount > 0 %}block{% else %}none{% endif %}"
                                      id="cart-total" class="text-center">{{ cart|length }}</span>
                            {% endwith %}
                        </a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item like mx-3 mx-sm-4 mx-md-3">
                            <a class="tool-link like-link" href="{% url 'shop:wishlist' %}">
                                <i class="fa-regular fa-heart"></i>
                                {% with wish_list|length as amount %}
                                    <span style="display: {% if amount > 0 %}block{% else %}none{% endif %}"
                                          id="wishlist-total" class="text-center">{{ wish_list|length }}</span>
                                {% endwith %}
                            </a>
                        </li>
                    {% endif %}
                    <li class="nav-item user ms-3 ms-sm-4 ms-md-3">
                        {% if user.is_authenticated %}
                            <div class="dropdown">
                                <a class="tool-link user-link" data-bs-toggle="dropdown" role="button"
                                   aria-expanded="false">
                                    <i class="fa-regular fa-user"></i>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-end pt-0">
                                    <li class="border-bottom py-1 mb-1">
                                        <a href="{% url 'personal_info' user.slug %}" style="padding-left: 11px">
                                            <img class="d-inline-block user-photo" alt=""
                                                 src="{% if user.photo %}{{ user.photo.url }}
                                                  {% else %}{% static 'img/default_avatar.jpg' %}{% endif %}">
                                            <h6 class="d-inline-block dropdown-header ps-1">{{ user.first_name }} {{ user.last_name }}</h6>
                                        </a>
                                    </li>
                                    <li><a class="dropdown-item" href="{% url 'personal_cabinet' %}">
                                        <i class="bi bi-person me-2 fs-6"></i>Особистий кабінет</a></li>
                                    <li><a class="dropdown-item" href="{% url 'order_list' %}">
                                        <i class="bi bi-gift me-2 fs-6"></i>Мої замовлення</a></li>
                                    <li><a class="dropdown-item" href="{% url 'logout' %}">
                                        <i class="bi bi-box-arrow-right me-2 fs-6"></i>Вийти з акаунту </a>
                                    </li>
                                </ul>
                            </div>
                        {% else %}
                            <a class="tool-link user-link" href="{% url 'login' %}?next={{ request.path }}">
                                <i class="fa-regular fa-user"></i>
                            </a>
                        {% endif %}
                    </li>
                </ul>
                <button class="navbar-toggler ms-4" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbar-collapse"
                        aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse order-md-1 justify-content-center" id="navbar-collapse">
                <ul class="navbar-nav mb-2 mb-md-0 text-center">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home' %}">Головна</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'shop:shop' %}">Магазин</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:blog' %}">Блог</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'about' %}">Про нас</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'contacts' %}">Контакти</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

templates/inc/_pagination.html
{% if page_obj.has_other_pages %}
    <div class="pagination my-4 justify-content-center">
        <div class="nav-links">
            {% if page_obj.has_previous %}
                <a class="page-numbers" href="?{{ s }}page={{ page_obj.previous_page_number }}{{ anchor }}">
                    <i class="fa fa-angle-left" aria-hidden="true"></i>
                </a>
            {% endif %}

            {% for p in page_obj.paginator.page_range %}
                {% if page_obj.number == p %}
                    <span class="page-numbers current">{{ p }}</span>
                {% elif p > page_obj.number|add:-3 and p < page_obj.number|add:3 %}
                    <a class="page-numbers" href="?{{ s }}page={{ p }}{{ anchor }}">{{ p }}</a>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <a class="page-numbers" href="?{{ s }}page={{ page_obj.next_page_number }}{{ anchor }}">
                    <i class="fa fa-angle-right" aria-hidden="true"></i>
                </a>
            {% endif %}
        </div>
    </div>
{% endif %}